### ISSUE TITLE
Error when trying text DNN classification with param 'validation_dataset_size' on GPU cluster

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/AutoML-vNext-Preview#4]
I got this error... But I'm not using cross-validation, but validation set split:
 
`Feature [enable_dnn] is unsupported due to incompatible values for argument(s):`

Train Dataset (To be uploaded as an AML Dataset named "newsgroups_train_data"):

https://automluipublicstorage.blob.core.windows.net/automl-devplat2-sample-datasets/classification/newsgroups_text-dnn-classification/newsgroups_train_data.csv

This is the .YAML:

https://github.com/Azure/automl-devplat2-preview/blob/main/examples/cli/classification/newsgroups-test-dnn-classification/01-newsgroups-test-dnn-classif-job-single-dataset.yaml
 
```
type: automl_job
name: 01-newsgroups-test-dnn-classif-job-single-dataset-110
experiment_name: Newsgroups-test-dnn-classif-CLI-Tests
compute:
  target: azureml:dnntext-cluster
general:
  task: classification
  primary_metric: accuracy
  enable_model_explainability: true
limits:
  job_timeout_minutes: 2400
  max_total_trials: 10
  max_concurrent_trials: 2
  enable_early_termination: true
data:
  training:
    dataset: azureml:newsgroups_train_data:1
    target_column_name: y
  validation:
    validation_dataset_size: 0.3
featurization:
  featurization_config: auto
  enable_dnn_featurization: true
training:
  blocked_training_algorithms: [LightGBM, XGBoostClassifier]
```
 
 
Which is aligned to this notebook:
 
MachineLearningNotebooks/auto-ml-classification-text-dnn.ipynb at master · Azure/MachineLearningNotebooks (github.com)

RUN ID:
01-newsgroups-test-dnn-classif-job-single-dataset-120

https://ml.azure.com/experiments/id/eb48af51-25e3-464d-887c-fe5b26af9fc0/runs/01-newsgroups-test-dnn-classif-job-single-dataset-120?wsid=/subscriptions/381b38e9-9840-4719-a5a0-61d9585e1e91/resourcegroups/cesardl-automl-eastus2euap-resgrp/workspaces/cesardl-automl-eastus2euap-ws&tid=72f988bf-86f1-41af-91ab-2d7cd011db47

RELATED BUG created in VSO:
https://msdata.visualstudio.com/Vienna/_workitems/edit/1143948
